x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

services:
  website:
    image: leafroute-web:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    depends_on:
      - db_migrate
      - mysql
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  db_migrate:
    image:  leafroute-web:latest
    command: python manage.py migrate
    volumes: *service-volumes
    depends_on:
      - mysql
    env_file:
      - ./.env

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: szakdoga
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: