# Generated by Django 5.2.5 on 2025-09-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_stage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule_st',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
