# Generated by Django 5.2.5 on 2025-10-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal_stage', '0002_alter_workschedule_st_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile_st',
            options={},
        ),
    ]
