# Generated by Django 5.2.5 on 2025-10-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_stage', '0003_alter_userprofile_st_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_st',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
