# Generated by Django 5.2.5 on 2025-10-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_stage', '0004_alter_order_st_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershipments_st',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
