# Generated by Django 5.2.5 on 2025-09-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinterest_userprofile_interests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('organiser_tasks', 'Is able to proceed with tasks related to organisers')]},
        ),
    ]
