# Generated by Django 5.2.5 on 2025-09-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('organiser_tasks', 'Is able to proceed with tasks related to organisers'), ('driver_tasks', 'Is able to proceed with tasks related to drivers'), ('warehouseman_tasks', 'Is able to proceed with tasks related to warehousemen'), ('manager_tasks', 'Is able to proceed with tasks related to managers')]},
        ),
    ]
