# Generated by Django 5.2.5 on 2025-09-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('dateid', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('monthname', models.CharField(blank=True, max_length=20, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('dayname', models.CharField(blank=True, max_length=20, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimOrder',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('orderstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('userfirstname', models.CharField(blank=True, max_length=255, null=True)),
                ('userlastname', models.CharField(blank=True, max_length=255, null=True)),
                ('useremail', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimProduct',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimRoute',
            fields=[
                ('routeid', models.AutoField(primary_key=True, serialize=False)),
                ('startcity', models.CharField(blank=True, max_length=255, null=True)),
                ('endcity', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimVehicle',
            fields=[
                ('vehicleid', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('fueltype', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactShipment',
            fields=[
                ('shipmentid', models.AutoField(primary_key=True, serialize=False)),
                ('shipmentstartdate', models.DateField(blank=True, null=True)),
                ('shipmentenddate', models.DateField(blank=True, null=True)),
                ('duration', models.DateTimeField(blank=True, null=True)),
                ('quantitytransported', models.IntegerField(blank=True, null=True)),
                ('fuelconsumed', models.IntegerField(blank=True, null=True)),
                ('co2emission', models.FloatField(blank=True, null=True)),
                ('transportcost', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('routecost', models.FloatField(blank=True, null=True)),
                ('unitprice', models.FloatField(blank=True, null=True)),
                ('consumption', models.FloatField(blank=True, null=True)),
                ('fuelcost', models.FloatField(blank=True, null=True)),
                ('productionyear', models.IntegerField(blank=True, null=True)),
                ('dateid', models.ForeignKey(db_column='DateID', on_delete=django.db.models.deletion.CASCADE, to='internal_dm.dimdate')),
                ('orderid', models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='internal_dm.dimorder')),
                ('productid', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='internal_dm.dimproduct')),
                ('routeid', models.ForeignKey(db_column='RouteID', on_delete=django.db.models.deletion.CASCADE, to='internal_dm.dimroute')),
                ('vehicleid', models.ForeignKey(db_column='VehicleID', on_delete=django.db.models.deletion.CASCADE, to='internal_dm.dimvehicle')),
            ],
        ),
    ]
