# Generated by Django 5.2.5 on 2025-09-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal_dm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dimdate',
            table='DIMDATE',
        ),
        migrations.AlterModelTable(
            name='dimorder',
            table='DIMORDER',
        ),
        migrations.AlterModelTable(
            name='dimproduct',
            table='DIMPRODUCT',
        ),
        migrations.AlterModelTable(
            name='dimroute',
            table='DIMROUTE',
        ),
        migrations.AlterModelTable(
            name='dimvehicle',
            table='DIMVEHICLE',
        ),
        migrations.AlterModelTable(
            name='factshipment',
            table='FACTSHIPMENT',
        ),
    ]
