# Generated by Django 5.2.5 on 2025-10-31 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_dm', '0002_alter_dimdate_table_alter_dimorder_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factshipment',
            name='dateid',
        ),
        migrations.AlterField(
            model_name='factshipment',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factshipment',
            name='shipmentenddate',
            field=models.ForeignKey(db_column='SHIPMENTENDDATE', on_delete=django.db.models.deletion.PROTECT, related_name='shipments_ended', to='internal_dm.dimdate'),
        ),
        migrations.AlterField(
            model_name='factshipment',
            name='shipmentstartdate',
            field=models.ForeignKey(db_column='SHIPMENTSTARTDATE', on_delete=django.db.models.deletion.PROTECT, related_name='shipments_started', to='internal_dm.dimdate'),
        ),
    ]
