# Generated by Django 5.2.5 on 2025-10-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_dm', '0003_remove_factshipment_dateid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimdate',
            name='dateid',
            field=models.IntegerField(db_column='DateID', primary_key=True, serialize=False),
        ),
    ]
